// nuxt/pages/projects.vue
<script setup lang="ts">
const { data, pending, error } = await useFetch('/api/projects')
</script>

<template>
  <main class="container">
    <h1>Proiectele mele</h1>
    <div v-if="pending">Se încarcă...</div>
    <div v-else-if="error">Eroare: {{ error?.message }}</div>
    <ul v-else>
      <li v-for="p in data" :key="p.id">
        <strong>{{ p.name }}</strong> — {{ p.status }}
      </li>
    </ul>
  </main>
</template>

<style>
.container { max-width: 760px; margin: 40px auto; padding: 0 16px; }
li { margin: 6px 0; }
</style>

// next/src/app/projects/page.tsx
async function getProjects() {
  const res = await fetch('http://localhost:3000/api/projects', { cache: 'no-store' })
  if (!res.ok) throw new Error('Failed to load projects')
  return res.json() as Promise<Array<{ id: number; name: string; status: string }>>
}

export default async function ProjectsPage() {
  const projects = await getProjects()
  return (
    <main className="mx-auto max-w-3xl p-6">
      <h1 className="text-2xl font-bold">Proiectele mele</h1>
      <ul className="mt-4 space-y-2">
        {projects.map(p => (
          <li key={p.id} className="rounded border p-3">
            <strong>{p.name}</strong> — {p.status}
          </li>
        ))}
      </ul>
    </main>
  )
}
