// next/src/app/login/page.tsx
import { redirect } from 'next/navigation'

export default function LoginPage() {
  const submit = async (formData: FormData) => {
    'use server'
    // TODO: integrate real auth later
    redirect('/projects')
  }

  return (
    <main className="mx-auto max-w-md p-6">
      <h1 className="text-2xl font-bold">Autentificare</h1>
      <form action={submit} className="mt-6 grid gap-3">
        <label className="grid gap-1">
          <span>Email</span>
          <input name="email" type="email" required className="rounded border px-3 py-2" />
        </label>
        <label className="grid gap-1">
          <span>Parolă</span>
          <input name="password" type="password" required className="rounded border px-3 py-2" />
        </label>
        <button className="mt-2 rounded bg-primary-600 px-4 py-2 font-semibold text-white hover:bg-primary-700">Intră în cont</button>
      </form>
    </main>
  )
}

// nuxt/pages/login.vue
<script setup lang="ts">
const router = useRouter()
const form = reactive({ email: '', password: '' })
function login() {
  // Placeholder: add real auth later
  router.push('/projects')
}
</script>

<template>
  <main class="container">
    <h1>Autentificare</h1>
    <form @submit.prevent="login">
      <label>Email
        <input v-model="form.email" type="email" required>
      </label>
      <label>Parolă
        <input v-model="form.password" type="password" required>
      </label>
      <button type="submit">Intră în cont</button>
    </form>
  </main>
</template>

<style>
.container { max-width: 480px; margin: 40px auto; padding: 0 16px; }
form { display: grid; gap: 12px; }
input { width: 100%; padding: 8px; }
button { padding: 8px 12px; font-weight: 600; }
</style>
